# Jekyll Slate Configuration

# Site settings
title: My Jekyll Site
email: your-email@example.com
description: "A description of my Jekyll site"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: slate
